#!/bin/bash
/system/install python-smbus
/system/install i2c-tools
/system/install build-essential 
/system/install python-dev 
/system/install python-smbus 
/system/install python-pip
/system/install git
pip install RPi.GPIO
git clone https://github.com/adafruit/Adafruit_Python_CharLCD /do/adafruitLCD/pythonLib
cd /do/adafruitLCD/pythonLib;python setup.py install
