#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[alpha] [gpio] [i2c] [electronics]"
	/show/usageDescription "Install Adafruit LCD shield Library"
	/show/usage "$0"
	exit 1
else
	/show/description "Adafruit LCD Shield module"
	/show/listecho "Check dependencies" $OK
	#Dependencies
	/system/install python-smbus
	/system/install i2c-tools
	/system/install build-essential
	/system/install python-dev
	/system/install python-smbus
	/system/install python-pip
	/system/install git
	/system/install python-rpi.gpio

	/show/listecho "Download library" $OK
	#Reclone if exists
	if [ -d /do/adafruitLCD/pythonLib ];then
	        rm -rf /do/adafruitLCD/pythonLib
	fi

	#Clone Adafruit Library
	/system/gitcloner adafruit/Adafruit_Python_CharLCD /do/adafruitLCD/pythonLib

	if [ -d /do/adafruitLCD/pythonLib ];then
		/show/listecho "Install library" $OK
		#Compile Adafruit Library
		cd /do/adafruitLCD/pythonLib;python setup.py install > /tmp/adafruit_lcd.log 2>&1

		/show/listecho "Enable I2C" $OK
		# Add I2C in /boot/config.txt
		/string/add "/boot/config.txt" "dtparam=i2c1=on"
		/string/add "/boot/config.txt" "dtparam=i2c_arm=on"

		# Reboot notification
		/show/listecho "You need to reboot to enable the LCD screen" $ERR
	else
		/show/listecho "I can't download Adafruit LCD library" $ERR
	fi
fi
